### ISSUE TITLE
pretty_midi missing from repo

### ISSUE THREAD

**Issue by bgenchel** [tensorflow/magenta#113]
I get this as an error when I attempt to import midi_io. Looking through both my local repo and the code hosted on github, it seems this dependency (pretty_midi) is not included? where can I find this library?

**Comment by hpssjellis** [comment]
I am having similar issues with midi files. Here is a pretty_midi repo

https://github.com/craffel/pretty-midi

**Comment by cghawthorne** [comment]
We don't directly include pretty_midi in our repo. Instead, we reference it in our WORKSPACE file[1]. This allows Bazel to download the repo whenever a python build target depends on it. Bazel also takes care of setting up the runfiles directory for that python target such that it can reference the pretty_midi repo.

For an example of how to do this, check out the build target for midi_io[2]. If you want to add your own targets that have a dependency on midi_io or pretty_midi within the repo, you'll need to define BUILD targets so that Bazel can manage the dependencies for you. You can find more information about how Bazel works at http://bazel.io.

1: https://github.com/tensorflow/magenta/blob/master/WORKSPACE
2: https://github.com/tensorflow/magenta/blob/master/magenta/lib/BUILD#L50
