### ISSUE TITLE
How to use MusicVAE under Python?

### ISSUE THREAD

**Issue by merfii** [tensorflow/magenta#1164]
I found no script for generating under musci_vae model. 
I wrote one based on **trained_model.TrainedModel** class.
The code is somewhat like this
```
 model = trained_model.TrainedModel(config, batch_size=1, checkpoint_path)
 z = model.encode(input_sequence)
 generated_sequences = model.decode(z[0], length=64, temperature=1)
magenta.music.sequence_proto_to_midi_file(generated_sequences[0], midi_path)
```
Then I found output had no relation with the input. Was there any thing wrong with my usage of Autoencoder?
Thank you for your answer!

**Comment by adarob** [comment]
Which checkpoint are you using or did you train your own?

Try using z[1], which doesn't have gaussian noise added.

**Comment by merfii** [comment]
@adarob 
I'm using my own checkpoint since there was no pretrained model given for MusicVAE.
Could give any example upon generating mid fie from MusicVAE-Python ?
Or show how to use music_vae.trained_model.TrainedModel correctly?

(I tried running examples of MusicVAE through Magenta.js, but converting checkpoint into that format was another mess-up ;-(

**Comment by adarob** [comment]
I haven't created a script or a download link because the intention was
that users would create samples through the colab notebook:
g.co/magenta/musicvae-colab

All of the code you would need to sample and create MIDIs there, along with
checkpoints. I may also add a binary to the project when I get time.

Hope this solves your problem!
