### ISSUE TITLE
MusicVAE: Add preprocess script.

### ISSUE THREAD

**Issue by adarob** [tensorflow/magenta#1199]

**Comment by PhilAScript826** [comment]
Hey I tried to use checkpoints to generate samples, but I get the below error.

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. 

I believe @jincong0623 mentioned the issue in the #1253 issue. Was this resolved? I tried to reference MusicVae colab notebook for assistance but I still couldn't get it to work.

**Comment by adarob** [comment]
Are you using the same config and hparams for generation as training?

**Comment by PhilAScript826** [comment]
Yeah I used the same.  I eventually was able to get the checkpoints to work.
