### ISSUE TITLE
ImportError: libcublas.so.9.0 [Tensorflow GPU with CUDA 10.0]

### ISSUE THREAD

**Issue by whyeverwhy** [tensorflow/magenta#1455]
Hello,

As Tensorflow currently supports only Cuda 9.0 [I believe except the nightly builds] I have installed a working version by following the guide here:
https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-ubuntu/

Then after installing magenta-gpu via pip to this virtualenv, it  broke the tensorflow-gpu and had to re-configure and re-install from the .whl again. The error I got was:
**libcublas.so.9.0: cannot open shared object file: No such file or directory** 

I'm wondering how can I fix this issue? Would "pip install magenta" work alone as tensorflow-gpu is already existent and fully functional in the virtualenv?

There are numerous topics regarding this error but none seemed relevant to my situation as the solution for most was to change the version of Tensorflow - which currently I can't to keep everything else stable.

**System:**
Ubuntu 18.04
Python 3.6.8
Tensorflow 1.12
CUDA 10.0
CuDNN 7.3.1
GPU RTX2080Ti

#1187 and #1407 [closed] seemed similar but due to various version differences I thought I could open a new issue.

Thanks very much.

**Comment by cghawthorne** [comment]
I suspect that your tensorflow installation has maybe gotten messed up due to the different packages. The `tensorflow` and `tensorflow-gpu` packages end up installing many of the same files and if you install one after the other, it will just overwrite a lot of those files. The only difference between `magenta` and `magenta-gpu` is whether the package depends on `tensorflow` or `tensorflow-gpu`.

If you need to use a custom compiled version of TensorFlow, I'd recommend the following:
- Install the `magenta` package.
- `pip uninstall tensorflow`, `pip uninstall tensorflow-gpu` (to ensure that you've removed all tensorflow files from your virtualenv)
- Install your custom built version of tensorflow.
