### ISSUE TITLE
Suitable location for adding documentation notebooks

### ISSUE THREAD

**Issue by falaktheoptimist** [tensorflow/magenta#1479]
Hi!
We have been exploring magenta for past few months and have made a notebook with musicxml documentation and showcasing functionalities of the parser. This is the first of several notebooks we're preparing which we feel would be beneficial to the user community. Any suggestions as to where we should put this? Could it be part of the magenta repo (we could send a PR) or should we start a separate repository for putting those?

Thanks!

**Comment by cghawthorne** [comment]
Thanks for creating that notebook! Is it intended to run as a local Jupyter notebook or a [Colab](https://colab.research.google.com)?

**Comment by falaktheoptimist** [comment]
Hi @cghawthone!
We made it with local usage in mind (users would need magenta of course). But with some modifications could be easily made into colab too I guess. We'd like to really get the notebooks published out and get some feedback before we go into more detail on the next ones.

**Comment by cghawthorne** [comment]
Hi @falaktheoptimist, we're thinking it would probably be best to use colab notebooks, just because the environment is a little more predictable. Would you mind converting your notebook into something that can work in colab and then making a PR to put it in a colab-notebooks directory in our [magenta-demos](https://github.com/tensorflow/magenta-demos) repo?

We'll then be able to load those notebooks directly in colab with links like  https://colab.research.google.com/github/tensorflow/magenta-demos/blob/master/colab-notebooks/NotebookName.ipynb

**Comment by falaktheoptimist** [comment]
Thanks @cghawthorne Done : https://github.com/tensorflow/magenta-demos/pull/64 The colab is now online and the link is there in the PR Readme.  [(Colab link)](https://colab.research.google.com/drive/1uxtG69W4vYjSF9NebsYSZnpnLoqa09aT)
Should we put the ipython notebook in there too and send a pull request?

**Comment by falaktheoptimist** [comment]
Notebook is now live.
