### ISSUE TITLE
How to train a sketch-rnn for interpolation between two objects?

### ISSUE THREAD

**Issue by giada1198** [tensorflow/magenta#1483]
Hi,

I am wondering how to train a sketch-rnn if I wanna realize the interpolation between two objects, such as the cat-bus and elephant-pig in your jupyter demo. I've tried to put multiple .npz files in the data_set parameter but it just messed up everything.

Thanks!

**Comment by hardmaru** [comment]
Hi @giada1198 

Are you able to train sketch-rnn on a single .npz file with your current setup?

Can you let me know the exact command you used, to see if I can reproduce the error?

Thanks

**Comment by giada1198** [comment]
@hardmaru thanks for your prompt reply, let me clarify my question:

I prepared two datasets: one is my hand-made small dataset(200/100/100), another is the airplane dataset from quick draw(7000/2500/2500). RNNs worked very well if I trained them individually. However, when I tried to trained them together in order to create some interesting interpolations, the outputs became a bunch of chaotic lines. I guess I used the wrong command:

```
python2 sketch_rnn_train.py --log_root='/home/giada1198/raw' --data_dir='/home/giada1198/raw' --hparams="data_set=[ren.npz, airplane.npz],enc_model=layer_norm,enc_rnn_size=512,save_every=500"
```
I used your [demo](https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN.ipynb) and merely changed the model path to generate outputs.

Thanks again!

**Comment by hardmaru** [comment]
Hi @giada1198 

I wonder if the data loader is doing something funky due to the big difference in dataset sizes between the two datasets.

If you have tried training sketch-rnn on both datasets (en.npz, airplane.npz) individually, and they both work, then a fix you can do is to manually concatenate the datasets together and train sketch-rnn on a single, combined npz file. To ensure that the random training batches are not skewed towards having mostly airplanes (since they dominate the in terms of the number of training samples), you may want to duplicate `en.npz` a few times so that the size is comparable, and perhaps use some data augmentation as well to avoid data fitting.

**Comment by giada1198** [comment]
@hardmaru sorry for my delayed reply. Thanks for your suggestion! Everything works very well now.
