### ISSUE TITLE
Question about Onsets and Frames Model

### ISSUE THREAD

**Issue by LegendFC** [tensorflow/magenta#1493]
I was finding something about automatic music transcription when I found this project. It is amazing. I wonder if there is any evaluation metric about the task of AMT.  It is about how to measure the accuracy of the model and how to define its performance.
In fact I've found some papers about the evaluation metric, such as a peper named 'evaluating automatic polyphonic music transcription' written by Andrew McLeod.  Maybe you can measure your model by this metric or another if you come up with a better one.

**Comment by cghawthorne** [comment]
@LegendFC We don't use the metrics in Andrew McLeod's paper because they deal more with a representation that is closer to sheet music, whereas our model currently just outputs a pianoroll/MIDI representation of the transcription. We instead use the suite of metrics that is collected in the [mir_eval](https://github.com/craffel/mir_eval) package. You can read more about exactly what metrics we use and our results in our two papers:

[Onsets and Frames: Dual-Objective Piano Transcription
](https://goo.gl/magenta/onsets-frames-paper)
[Enabling Factorized Piano Music Modeling and Generation with the MAESTRO Dataset](https://goo.gl/magenta/maestro-paper)
