### ISSUE TITLE
README.md is not able to follow on Google Cloud Platform.

### ISSUE THREAD

**Issue by yemugogogo** [tensorflow/magenta#1518]
Reproducible steps:
1. Google Cloud Console -> Create VM -> Google Drawfork Ubuntu 16.04 LTS
2. Configuration: n1-8highcpu / 7.2G Memory
4. chmod a+w ~/  # https://github.com/conda/conda/issues/6748
5. Follow https://github.com/tensorflow/magenta
6. curl https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/magenta-install.sh > /tmp/magenta-install.sh && bash /tmp/magenta-install.sh 2>&1  | tee stderrout.log.txt
7. yes -> ENTER -> yes (initialize Miniconda2) -> y [NEW packages like pip]

Outstanding error message:

/home/itspeter_google_com/miniconda2/etc/profile.d/conda.sh: line 59: CONDA_PREFIX: readonly variable
[2019-04-28T16:52:29+0000]: Did not successfully activate the magenta conda environment

===========================================
Installation did not finish successfully.
Please follow the manual installation instructions at:
https://github.com/tensorflow/magenta
===========================================
[stderrout.log.txt](https://github.com/tensorflow/magenta/files/3125207/stderrout.log.txt)

**Comment by Jishanshaikh4** [comment]
It is true that creating a new conda environment (https://github.com/conda/conda/issues/6748) faces issues when the root directory is read only; this is probably because conda requires to create temporary files in root directory for environment management and storage purposes, and read only mode does not let it to do so. The error is in line 59 of file /home/itspeter_google_com/miniconda2/etc/profile.d/conda.sh requires execution permission for variable CONDA_PREFIX. You can try giving executable permission to all conda variables, as most likely more than one variables may require executable permissions. Is your current user have administration privileges? Try giving it so might help it.

**Comment by cghawthorne** [comment]
For cases where the auto-install script fails, you can also try the manual installation instructions. Please reopen the bug if either of these solutions don't fix the issue.

**Comment by adriagil** [comment]
> giving executable permission to all conda variables

How to do that exactly?
I'm not a master in Python so any help would be appreciated.
I have the same problem when trying to install Magenta on my computer.

> For cases where the auto-install script fails, you can also try the manual installation instructions. Please reopen the bug if either of these solutions don't fix the issue.

I'm trying also to do it manually but still getting some errors so I can't install Magenta at all.
I've already opened a but here https://github.com/tensorflow/magenta/issues/1546
