### ISSUE TITLE
MusicVAE - Training stops at epoch 0 with no output or explanation.

### ISSUE THREAD

**Issue by LucaAngioloni** [tensorflow/magenta#1549]
Magenta version: 1.1.2
TensorFlow version: 1.13.1

Environments: Google Colab (GPU, Python3), also MacOS (CPU, Python 3.5) and Ubuntu (CPU, Python 3.5).

I tried more environments to see if that was the cause... No luck.

-----------------------

I am using MusicVAE with a custom config:

```
CONFIG_MAP['drums_4bar'] = Config(
    model=MusicVAE(
        lstm_models.HierarchicalLstmEncoder(
            lstm_models.BidirectionalLstmEncoder, [16, 4]),
        lstm_models.HierarchicalLstmDecoder(
            lstm_models.SplitMultiOutLstmDecoder(
                core_decoders=[
                    lstm_models.CategoricalLstmDecoder()],
                output_depths=[
                    512,  # drums
                ]),
            level_lengths=[16, 4],
            disable_autoregression=True)),
    hparams=merge_hparams(
        lstm_models.get_default_hparams(),
        HParams(
            batch_size=256,
            max_seq_len=64,
            z_size=128,
            enc_rnn_size=[512],
            dec_rnn_size=[512, 512],
            free_bits=256,
            max_beta=0.2,
        )),
    note_sequence_augmenter=None,
    data_converter=data.DrumsConverter(
        max_bars=4,  # Truncate long drum sequences before slicing.
        slice_bars=4,
        steps_per_quarter=4,
        roll_input=True),
    train_examples_path=None,
    eval_examples_path=None,
)
```

and with a custom dataset that contains a few thousands of midi files of exactly 4-bars length quantised at 1/16th of drums playing. I created it following [this guide](https://github.com/tensorflow/magenta/blob/master/magenta/scripts/README.md) on the official documentation. No error here.

When I start training, it stops as soon as epoch 0. It saves the model checkpoint and just returns with no other output.

Output sample (last lines):
```
INFO:tensorflow:Create CheckpointSaverHook.
I0620 11:55:18.037413 4793398720 basic_session_run_hooks.py:527] Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
I0620 11:55:28.968688 4793398720 monitored_session.py:222] Graph was finalized.
INFO:tensorflow:Running local_init_op.
I0620 11:55:33.388229 4793398720 session_manager.py:491] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0620 11:55:34.830129 4793398720 session_manager.py:493] Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./train/model.ckpt.
I0620 11:56:07.883282 4793398720 basic_session_run_hooks.py:594] Saving checkpoints for 0 into ./train/model.ckpt.
2019-06-20 11:57:14.444228: W ./tensorflow/core/framework/model.h:202] Encountered a stop event that was not preceded by a start event.
```
--------------------

From the few tests I ran, it seems dependent on the Dataset. In fact I used an other custom dataset that contains a few thousands of midi files of exactly 8-bars length (instead of 4) quantised at 1/16th and it works. It trains just fine. It generates new samples just fine.

How can I debug this and understand were it fails, which midi files generate the problem?

**Comment by quantumpencil** [comment]
I fixed this exact issue for the hierarchical VAE model's recently. In my case, it was caused by the training samples being rejected -- due to an issue with the way parts were being encoded in my output midi compared to what the TrioConverter was expecting . You've probably got a similar issue here. 

I recommend you add some logging in DrumConverter (it's in data.py, a subclass of BaseNoteSequenceConverter)'s _to_notesequences method, to the base class'  to_tensors method, and the get_dataset method here https://github.com/tensorflow/magenta/blob/b0c89b086c74248096c265541b6e84b2af61e9ff/magenta/models/music_vae/data.py#L1189

The last one is invoked during training, and uses the data converter from the config in its subs to transform note-sequences into the actual tensors that feed into the model. Your issue is most likely that due to some kind of malformed midi, the notesequence protos that are being created when you run the note-sequenced converter (the building your data set step in the docs) are not accepted by the DrumsConverter that your model invokes.

**Comment by LucaAngioloni** [comment]
Thank you. 
My problem was very similar to yours and you were on point. 
I was able to fix it changing my data (MIDI) structure. 
Unfortunately the converter didn't provide any useful info without the new layer of debugging that you suggested.

**Comment by fredy0219** [comment]
Hi I have the same issue, did anyone solve this problem?

Is there anyway to explain what the exactly right MIDI structure manual to follow?
