### ISSUE TITLE
score2perf;  t2t_datagen.py running endlessly

### ISSUE THREAD

**Issue by Joviistos** [tensorflow/magenta#1555]
Thanks for the wonderful Music Transformer. Can't wait to get it going!

I have this issue when I run a t2t_datagen.py script. I have this following output that keeps running endlessly:

[console-output.txt](https://github.com/tensorflow/magenta/files/3353369/console-output.txt)

I am using Google Colab
Python 2.7

and running these options
 
PIPELINE_OPTIONS="--runner='DataflowRunner',"\
"--project=kaggle-241007,"\
"--temp_location=gs://music_gen/tmp,"\
"--setup_file=magenta/setup.py"

!python magenta/magenta/tensor2tensor/t2t_datagen.py \
  --data_dir='gs://music_gen/datagen' \
  --problem='score2perf_maestro_language_uncropped_aug' \
  --pipeline_options=PIPELINE_OPTIONS \
  --alsologtostderr\

when I omit the  ' --pipeline_options=PIPELINE_OPTIONS ' I get the same output

**Comment by iansimon** [comment]
Not sure if the pasted text is your exact command, but I think you need a $ in the flag: `--pipeline_options=$PIPELINE_OPTIONS`

From your pasted log, it looks like it's not finding your specified pipeline options and trying to use the DirectRunner on your local machine instead of the DataflowRunner.
