### ISSUE TITLE
Midi2Wave network details

### ISSUE THREAD

**Issue by sukun1045** [tensorflow/magenta#1661]
In the paper of the Maestro data-set, there is the midi2wave part which is a conditional wavenet but I couldn't find it in magenta repository. So I have several questions for you.
1. What does the context stack mean here and how exactly the 2 context stacks are implemented? Actually the information of context stacks are few in the wild. From my own understanding, two context stacks mean that there is a "shorter range" wavenet, and a "longer range" wavenet. The two wavenets jointly comprise the "context stack". The shorter range wavenet locally conditions on an input. That input is the output of the "longer-range" wavenet, which has a receptive field of, say, 5 seconds. I couldn't relate this idea with what has been mentioned in the paper "a deeper context stack, namely 2 stacks with 6 layers each arranged in a series..." and,"the input to the context stack is a size-88 vector". Will you clarify it a little bit?
2. What is the sampling rate of audio waveform when you train that conditional wavenet?
3. How many samples/How long will the audio waveform be trained in that conditional wavenet at once? Any segmentation technique for choosing the training samples?

Look forward to seeing your reply, 
Thank you.

**Comment by drzraf** [comment]
I've two additional questions about the model and thought I'd add them here instead of creating a new issue for this.

@sukun1045 : About your point n°2 : according to the [paper](https://arxiv.org/pdf/1810.12247.pdf), the audio recordings used where:
> (44.1–48 kHz 16-bit PCM stereo)

**but** current code states:
https://github.com/tensorflow/magenta/blob/600ba5438d523f8286c87a34b39be9276e69897a/magenta/models/onsets_frames_transcription/realtime/onsets_frames_transcription_realtime.py#L42-L43



That being said, the paper also states that
> The input to the context stack is an onset “piano roll” representation, a size-88 vector signaling the onset of any keys on the keyboard, with 4ms bins (250Hz).

(quite a high resolution)

**But**, @cghawthorne, the [onsets_frames_wavinput.tflite](https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/tflite/onsets_frames_wavinput.tflite) input tensors expect a list of **17.920** samples (float).
Given that it also explicitly expects them to be float-32 collected from 16khz mono-sampling, that means that it needs exactly 1.12 seconds of audio... (Not quite  _realtime_ ;))

My first reaction was that I'd love to see a variant of [onsets_frames_wavinput_no_offset_uni.tflite](https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/tflite/onsets_frames_wavinput_no_offset_uni.tflite) accepting ~20-30ms worth of audio

Question 1:
> **What made this model restricted to this huge quantity of samples?**

Note 1:
Output tensors are structured so to provide 32 "chronological buckets".
If I'm right, that means that these 17920 samples (at 16khz, being 1.12s worth) are split in chunks of 35ms and there is **apparently** nothing stopping the model from being fed with a 560-floats buffer (right-padded with `00000...` to fit input tensors size) and only collect the first output tensor's bucket but...

Question 2: Could you please confirm that being a possible and adequate way to feed the model if we want 30ms-like delays?

Thank you!

**Comment by mtyka** [comment]
Q1: The model consists of an early CNN followed by an BiLSTM (or simple LSTM) which integrates the date in the time direction across a long sample. In the original model the *entire* performance (many seconds) is treated together as one block, with LSTMs running forward and backward in time. I.e. the individual chunks are not independent from each other. For the tflite version we needed to shorten the block to make it manageable as the entire LSTM is unrolled statically. 
2) No it's not possible to run the BiLSTM version in 30ms chunks. 
2b) Yes theoretically it's possible to run the UnidirectionalLSTM version in chunks but you'd also have to manually manage the LSTM states from chunk to chunk which is awkward, to say the least.

**Comment by cghawthorne** [comment]
I think some of the confusion comes from the [paper](https://goo.gl/magenta/maestro-paper) talking about several models and also a dataset. The [MAESTRO](https://g.co/magenta/maestro-dataset) dataset has audio that was recorded in 44.1–48 KHz 16-bit PCM stereo, but the [Onsets and Frames](http://goo.gl/magenta/onsets-frames-code) model downsamples it to 16 KHz mono before using it. It would certainly be possible to train a model using the full samplerate of the dataset, it's just something we haven't fully explored.

The part of the paper that talks about a 4ms resolution pianoroll is referring to the Midi2Wave synthesis model, which is a completely separate codebase from the transcription model (and is unfortunately not currently open sourced).

**Comment by richt3211** [comment]
@cghawthorne Are there plans to open source the WaveNet model that is used for the Midi2Wave in the future? It would be extremely nice to be able to use it for piano music synthesis, even for music that is not part of the MAESTRO dataset.
