### ISSUE TITLE
Adding sustain pedal control as a new performance event

### ISSUE THREAD

**Issue by gudgud96** [tensorflow/magenta#1691]
Greetings Magenta authors,

Thank you for the wonderful effort of building Magenta.

Will it be a good idea if the sustain pedal control (or MIDI control changes in general) can be included as a new performance event [here](https://github.com/tensorflow/magenta/blob/fa09b5ef1e9f5b961d64a058af806d1060ea1162/magenta/music/performance_lib.py#L46)?

Reason: When MidiPerformanceEncoder is used solely to encode & decode MIDI files, all control events will not be captured after the encode-decode process. In terms of piano performance modelling, control changes such as sustain pedal and soft pedal can be crucial for the output results.

Thank you for your consideration once again!

**Comment by cghawthorne** [comment]
Hi @gudgud96! It's definitely possible to do it that way. Thus far, we've just been using `sequences_lib.apply_sustain_control_changes` to lengthen notes played under sustain. It doesn't capture all the subtleties of sustain pedal usage, but it at least accounts for notes playing longer.

We haven't explored more direct pedal modeling at this point because a lot of our data comes from [transcriptions](https://magenta.tensorflow.org/piano-transformer), and our [transcription model](https://g.co/magenta/onsets-frames) does not currently do anything to predict pedal usage.

If you get interesting results from a more direct modeling of pedal usage, we'd love to hear about them!
