### ISSUE TITLE
Use the environment python

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/magenta#199]
Seems that bazel or some script defaults to /usr/bin/python when generating the magenta scripts.
It would be nice if we could support the current virtualenv/conda env python path.

**Comment by cghawthorne** [comment]
@Mistobaan do you have some pointers on what that change would look like?

**Comment by jfsantos** [comment]
Probably just changing from `/usr/bin/python` to `/usr/bin/env python` everywhere should do the trick.

**Comment by cghawthorne** [comment]
I looked into this a little more. The only way I know to fix this completely with Bazel would be to use a bazel.rc template that is filled out by a configure script, similar to what Tensorflow does: https://github.com/tensorflow/tensorflow/blob/master/tools/bazel.rc.template

A configure script seems a little heavy for Magenta, but there are a couple ways to make this work a little better:

- Make sure you do a `bazel shutdown` after changing conda/virtualenv environments. This will force bazel to re-evaluate the location of the python interpreter.

- Instead of using bazel, use our new pip package to install the Magenta scripts. We released this just last week and updated the main README file with instructions on how to use it.
