### ISSUE TITLE
basic_rnn

### ISSUE THREAD

**Issue by vmeade** [tensorflow/magenta#219]
I'm trying to run basic_rnn in the example but the absolute path of the BUNDLE_PATH can not find the basic_rnn.mag file :-/

any suggestions?

**Comment by elburz** [comment]
Did you download the file basic_rnn.mag and put it on the machine? It's one of the steps listed on this page under Pre-Trained. You can download it and put it in the shared folder you designated, then use the `BUNDLE_PATH=<path_here.mag>` to point at the downloaded file.

https://github.com/tensorflow/magenta/tree/master/magenta/models/basic_rnn

**Comment by elburz** [comment]
Also noticed you can just skip the step because the download should already be there. So you can change this

`BUNDLE_PATH=<absolute path of basic_rnn.mag>

bazel run //magenta/models/basic_rnn:basic_rnn_generate -- \
--bundle_file=${BUNDLE_PATH} \
--output_dir=/tmp/basic_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"`

And instead just point to the bundle_file in the flags like:

`bazel run //magenta/models/basic_rnn:basic_rnn_generate -- \
--bundle_file=/magenta-models/basic_rnn.mag \
--output_dir=/tmp/basic_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"`
