### ISSUE TITLE
MusicXML Parser: Add ability to indicate partial measures (e.g., pickup measure)

### ISSUE THREAD

**Issue by cghawthorne** [tensorflow/magenta#357]
We would eventually like to train models to understand what kinds of things are more common on different beats within measures. For example, it might learn that certain harmonies are more common on "strong" beats (e.g., 1 & 3). In order to do this, we would need to know where notes are within a measure.

For pieces with no partial measures, we have all the information we need. The combination of tempo, time signature, and note duration is sufficient to determine which measure a note is in and what beat within the measure (use tempo to calculate how long a quarter note is, use time signature to determine how many of those durations are in a measure).

However, for pieces with a pickup measure at the beginning (or other kinds of partial measures), this calculation will always be incorrectly offset by the duration of the pickup measure. For example, if a piece is in 4/4 and has a 1-beat pickup measure, we would incorrectly assume that the first 4 beats make up the first measure, when it is actually the first 4 beats _after_ the first pickup beat.

To solve this problem, we should add in new TimeSignature messages to indicate implicit time signature changes within pieces. For example, if a 4/4 piece has a 1-beat pickup measure, several full measures, and a 3-beat final measure, it would have 3 TimeSignature messages: 1/4 for the first measure, 4/4 after that, and a final 3/4 time signature at the end.

**Comment by cghawthorne** [comment]
@jsawruk is this something you would be interested in?

**Comment by jsawruk** [comment]
I think that's doable because we know the cumulative duration within a single measure. For example, I generated a MusicXML file in 4/4 with a 1 beat pickup. In measure 0, it set divisions to 256 and had a note of duration 256. In measure 1, divisions continued as 256, and the whole note had a duration of 1024. (Please see attached example file).

This demonstrates that any partial measure would just be the maximum of the sum of the note durations across all voices with that measure (some voices may only appear partially within a given measure). In the above example, if the durations summed to 512, then a 2/4 TimeSignature would be inserted. 

MusicXML does not enforce that the durations fit within a measure, so we can expand this if a measure overflows, i.e. there are 5 beats in a measure of 4/4.
[pickup_bar.xml.zip](https://github.com/tensorflow/magenta/files/572919/pickup_bar.xml.zip)

**Comment by jsawruk** [comment]
Here's a proposed solution:
- When beginning a new measure, check if there is a previous measure. 
- If there is, find the sum of its durations in voice 1 (since voice 1 is always present)
- Build a time signature as proper fraction in lowest terms (ex: 3/8 instead of 1.5/4)
- If the time signature is different from the current global time signature (in the parser state):
  - Insert the new time signature into the previous measure at the beginning. Time signatures cannot be inserted in the middle of a measure
  - Update the global time signature in the parser state.

Three examples/test cases:

1. First measure, full measure of 4/4. The MusicXML contains time signature info describing this measure as 4/4 (this sets the global time signature to 4/4). 
  - The total duration = 1024, and divisions = 256, which gives a time signature of 4/4. 
  - Because 4/4 = 4/4, no action is taken. 
  - These computations occur in measure 2 because that is the only way to ensure we have exited the measure.

2. First measure, pickup measure of 1 beat, but the MusicXML contains time signature info of 4/4. This sets the global time signature to 4/4.
  - When entering measure two, compute the total duration of the previous measure (measure 1).
  - Total duration = 256, divisions = 256. Computed time signature = 1/4.
  - 1/4 != 4/4. Insert a 1/4 time signature in the first measure. Update the global time signature to 1/4.
  - When entering measure three, compute the total duration of the previous measure (measure 2).
  - Total duration = 1024, divisions = 256. Computed time signature = 4/4
  - 4/4 != 1/4. Insert a 4/4 time signature in the second measure. Update the global time signature to 4/4.

3. First measure, pickup measure of 3 eighth notes (1.5 quarter notes). The MusicXML indicates a time signature of 4/4, setting the global time signature to 4/4.
  - Same as 2 above, but now the computed time signature = 3/8.
  - When in measure 2, insert the 3/8 time signature into measure 1 and update the global time signature
  - When in measure 3, 3/8 != 4/4, so insert the time signature change into measure 2 and update the global time signature to 4/4.

**Comment by cghawthorne** [comment]
Sounds like a good plan!

The st_anne.xml file I'm adding in #356 might be a good test file to use for this change because it has some partial measures in it.

**Comment by jsawruk** [comment]
I've changed the algorithm slightly after looking at the st_anne.xml example. Instead of computing the new time signature when parsing the next measure, compute it after parsing the current measure. This occurs within the Part class. As a result, there is no longer any need to keep track of the previous measure. The other details remain the same.

**Comment by jsawruk** [comment]
We also have to add the following test cases in addition to st_anne.xml. 

1. Measure 1 does not have a time signature defined at all. See for example Messiaen's Quartet for the End of Time, Movement 6 "Danse de la fureur". In that particular example, the inserted time signature for the first measure would be 17/16.

2. Parts 1 and 2 have different time signatures, but the barlines are coordinated. For example, Part 1 could be in 4/4, but Part 2 could be in 12/8.

3. Parts 1 and 2 have different time signatures, but the barlines are explicitly not coordinated. For example, Part 1 could be in 4/4 and Part 2 could be in 3/4. (It is also possible to write music where 4/4 and 3/4 have coordinated barlines, but in that case the tempo would be different. That use case would be covered by #2 above).

I am working on constructing public domain examples of the above.
