### ISSUE TITLE
Could not open alsa sequencer as a client. alsa midi patchbay will be not available

### ISSUE THREAD

**Issue by neovaldivia** [tensorflow/magenta#561]
When attempting to run qjacktctl I get a pop up with this message:
could not open alsa sequencer as a client. alsa midi patchbay will be not available

Also the following message in the command line:
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server
Could not initialize OpenGL for RasterGLSurface , reverting to RasterSurface

All attempts to continue with the Set up fail with multiple additional errors.
I'm on AWS BTW.

**Comment by cghawthorne** [comment]
I don't think you'll be able to run the MIDI interface on AWS. There may be a way to get it to run without a local soundcard, but I'm not sure how to set up all the components to work that way. I'd suggest either running it locally or just using the generation scripts rather than an interactive environment.

If you want an easy way to play around with an interactive Magenta environment, I'd also suggest you check out AI Duet: https://aiexperiments.withgoogle.com/ai-duet
