### ISSUE TITLE
Error running sketch rnn jupyter notebook

### ISSUE THREAD

**Issue by pcuellar** [tensorflow/magenta#760]
I'm trying to run the sketch rnn documented on the python notebook. When running:

`[train_set, valid_set, test_set, hps_model, eval_hps_model, sample_hps_model] = load_env(data_dir, model_dir)`

I get the following error:

> .../anaconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.pyc in load_env(data_dir, model_dir)
        74   with tf.gfile.Open(os.path.join(model_dir, 'model_config.json'), 'r') as f:
        75     model_config = json.load(f)
---> 76     model_params.update(model_config)
        77   return load_dataset(data_dir, model_params, inference_mode=True)
        78 `
AttributeError: 'HParams' object has no attribute 'update'

Any help will be greatly appreciated.

**Comment by hardmaru** [comment]
will take a look

**Comment by hardmaru** [comment]
Hi @pcuellar 

In sketch_rnn_train.py, in line 75, I see something different than what you are seeing:

https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py#L75

Recently, the Params object has been updated to use tf's HParams and update has been changed to parse_json a week or two ago. Maybe you need to run the latest version.

If the latest packaged version doesn't include the latest code, we will need to release and update the packages so that they do.

Thanks
