### ISSUE TITLE
Docker image with gpu support?

### ISSUE THREAD

**Issue by HandsomeDevilv112** [tensorflow/magenta#775]
My apologies if I just missed this somewhere, but is there a version of the docker that has cuda support? Or is there a way to use the nvidia-docker that I haven't quite grasped?
Thanks!

**Comment by cghawthorne** [comment]
We don't currently have a pre-built Magenta image with gpu support. However, it should be fairly easy to build one. Just modify the [Dockerfile](https://github.com/tensorflow/magenta/blob/master/magenta/tools/docker/Dockerfile) to depend on `tensorflow/tensorflow:N.N.N-devel-gpu` instead of the version without `-gpu`, and that should work.
