### ISSUE TITLE
Changes for Python 3 needed in interfaces/midi/midi_hub.p

### ISSUE THREAD

**Issue by CircuV** [tensorflow/magenta#859]
The ones I spotted were:

The Queue module has to be changed to queue to work in Python3.

iteritems() has to be changed to items()  for Python 3.

**Comment by eps696** [comment]
hello dear sirs 
any progress on making magenta_midi work with python 3? 
issue is still open, so there's a hope yet..

**Comment by adarob** [comment]
Sorry but this is not something I'll be able to work on in the near future. Can you try using Python2 instead? Also, external contributions are welcome!

**Comment by eps696** [comment]
Adam, thanks for replying! 
Could you maybe give some hints - what directions to go / which modules to check - to try fixing this or find some workaround? I can definitely invest some time in this issue, but my TF knowledge is rather limited yet, and it's pretty tricky to dissect your system without prior knowledge 'what does what'.
As for Py2 - alas, i'm on Windows (and have to stay with it for reasons) and TF does not support Python 2 on Win platform in general (let alone the very last 1.12 version).

**Comment by eps696** [comment]
ouch, it seems i mixed up two threads - current problem is in this one (opened by the same guy and you as assignee): https://github.com/tensorflow/magenta/issues/860
that is, midi interface stops getting any input after first response. and it's pretty hard to debug (i spent few days already with no success). 

btw this issue seems fixed already - in the last version `queue` is imported from `six` and there are no `iteritems` in the code (and obviously all imports are ok - that would be easy to fix)

**Comment by adarob** [comment]
Closing this one since it is fixed according to @eps696.
