### ISSUE TITLE
Nsynth: Implement Distilled Wavenet

### ISSUE THREAD

**Issue by veqtor** [tensorflow/magenta#960]
Hoping that magenta team will port the Distilled Wavenet implementation to Nsynth!
Parallel WaveNet: Fast High-Fidelity Speech Synthesis - DeepMind:
https://deepmind.com/blog/high-fidelity-speech-synthesis-wavenet/

**Comment by jesseengel** [comment]
Thanks for the enthusiasm! Distillation is a cool trick, and we've worked with the authors, but it is a non-trivial amount of work to adapt to something like NSynth because of the multi-step training and broader range of timbres in the dataset, so I don't see us working on that any time soon. We _are_ very excited about some work coming down the line for efficient and maybe realtime audio synthesis, so stay tuned!
