### ISSUE TITLE
error when running evaluating the model script

### ISSUE THREAD

**Issue by Calvin-Shen** [tensorflow/magenta#982]
I just runed a training model script like
 'polyphony_rnn_train \
--run_dir=/tmp/polyphony_rnn/logdir/run1 \
--sequence_example_file=/tmp/polyphony_rnn/sequence_examples/training_poly_tracks.tfrecord \
--hparams="batch_size=64,rnn_layer_sizes=[64,64]" \
--num_training_steps=20000'
and successfully running.
in parallel I runed the evaluating script like '
polyphony_rnn_train \
--run_dir=/tmp/polyphony_rnn/logdir/run1 \
--sequence_example_file=/tmp/polyphony_rnn/sequence_examples/eval_poly_tracks.tfrecord \
--hparams="batch_size=64,rnn_layer_sizes=[64,64]" \
--num_training_steps=20000 \
--eval'
occurred error like 'tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to calculate temp_storage_bytes, status: out of memory
	 [[Node: cond_1/Where = Where[_device="/job:localhost/replica:0/task:0/device:GPU:0"](cond_1/SequenceMask/Less/_161)]]
	 [[Node: mean_1/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch/_203 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_480_mean_1/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]'

Anyone can tell me what causes this problem?and how to solve it? thanks a lot~
@cghawthorne

**Comment by cghawthorne** [comment]
You probably won't be able to run both training and evaluation on the GPU on the same machine. I'd recommend running the eval job on just CPU. You can do this by running `export CUDA_VISIBLE_DEVICES=''` before starting the eval job.

**Comment by cghawthorne** [comment]
By default, the eval job expects a new checkpoint every 5 minutes or else it will timeout: https://github.com/tensorflow/magenta/blob/master/magenta/models/shared/events_rnn_train.py#L89

This usually isn't a problem because checkpoints are saved every minute: https://github.com/tensorflow/magenta/blob/master/magenta/models/shared/events_rnn_train.py#L20

But it could happen if your training setup is very slow. You could try altering that code to have a longer timeout, but if your training is really taking >5 minutes for a single step, it might be better to try to find a faster training environment.
